/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ppfuns_filemanager_jni_NetBiosUtil */

#ifndef _Included_com_ppfuns_filemanager_jni_NetBiosUtil
#define _Included_com_ppfuns_filemanager_jni_NetBiosUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ppfuns_filemanager_jni_NetBiosUtil
 * Method:    getTcpSv
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ppfuns_filemanager_module_SmbScanner_getTcpSv
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_ppfuns_filemanager_jni_NetBiosUtil
 * Method:    getUdpSv
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ppfuns_filemanager_module_SmbScanner_getUdpSv
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
